use  employeeDB;
create table CUSTOMER(ACCNO int,CUST_NAME char(100));
ALTER TABLE CUSTOMER ALTER COLUMN CUST_NAME VARCHAR(100);

ALTER TABLE CUSTOMER ALTER COLUMN CUST_NAME VARCHAR(50);
SELECT*FROM CUSTOMER;
INSERT INTO CUSTOMER VALUES(123456,'ISHWAR ACADEMY');
ALTER TABLE CUSTOMER ALTER COLUMN CUST_NAME VARCHAR(15);
ALTER TABLE CUSTOMER ALTER COLUMN CUST_NAME CHAR(50);
